DROP TABLE P_MEMBER CASCADE CONSTRAINTS;
CREATE TABLE P_MEMBER (
	ID			VARCHAR2(20) PRIMARY KEY 
	, PWD			VARCHAR2(20) NOT NULL
	, NICK_NM		VARCHAR2(30) NOT NULL
	, EMAIL 		VARCHAR2(50) NOT NULL
	, JOIN_DATE 	DATE DEFAULT SYSDATE NOT NULL
	, LAST_UPDATE	DATE
	, GRADE			VARCHAR2(20) DEFAULT '일반회원' NOT NULL
);

INSERT INTO EZEN.P_MEMBER (ID, PWD, NICK_NM, EMAIL)
VALUES('apple', '0001', '사과', 'apple@gmail.com');
INSERT INTO EZEN.P_MEMBER (ID, PWD, NICK_NM, EMAIL)
VALUES('banana', '0002', '바나나', 'banana@naver.com');
INSERT INTO EZEN.P_MEMBER (ID, PWD, NICK_NM, EMAIL)
VALUES('chocolate', '0003', '초코', 'chocolate@gmail.com');
INSERT INTO EZEN.P_MEMBER (ID, PWD, NICK_NM, EMAIL)
VALUES('dorazi', '0004', '도라지', 'dorazi@daum.net');
INSERT INTO EZEN.P_MEMBER (ID, PWD, NICK_NM, EMAIL)
VALUES('egg', '0005', '계란', 'egg@kakao.co,kr');
ROLLBACK;
COMMIT;

DROP TABLE P_BOARD CASCADE CONSTRAINTS;
CREATE TABLE P_BOARD (
	POST_NUM		NUMBER PRIMARY KEY
	, ID  			VARCHAR2(20) NOT NULL
	, BOARD_NUM 	NUMBER(1) NOT NULL
	, POST_CATE		NUMBER(2) NOT NULL
	, POST_TITLE	VARCHAR2(100) NOT NULL
	, POST_CONTENT	VARCHAR2(4000) NOT NULL
	, POST_DATE 	DATE DEFAULT SYSDATE NOT NULL
	, VISITCOUNT	NUMBER DEFAULT 0 NOT NULL
	, COUNT_COMMENT NUMBER
	, OFILE			VARCHAR2(200)
	, SFILE 		VARCHAR2(30)
	, FOREIGN KEY(ID) REFERENCES P_MEMBER (ID)
);

INSERT INTO EZEN.P_BOARD (POST_NUM, ID, BOARD_NUM, POST_CATE, POST_TITLE, POST_CONTENT)
VALUES(seq_BOARD_num.nextval, 'apple', 1, 11, '사과먹고싶다.', '빨간사과 파란사과');
INSERT INTO EZEN.P_BOARD (POST_NUM, ID, BOARD_NUM, POST_CATE, POST_TITLE, POST_CONTENT)
VALUES(seq_BOARD_num.nextval, 'banana', 2, 12, '바나나는 길어', '길으면 기차');
INSERT INTO EZEN.P_BOARD (POST_NUM, ID, BOARD_NUM, POST_CATE, POST_TITLE, POST_CONTENT)
VALUES(seq_BOARD_num.nextval, 'chocolate', 1, 13, '달달한 초코렛', '기브 미 초코렛');
INSERT INTO EZEN.P_BOARD (POST_NUM, ID, BOARD_NUM, POST_CATE, POST_TITLE, POST_CONTENT)
VALUES(seq_BOARD_num.nextval, 'dorazi', 2, 14, '도라지', '도라치무침');
INSERT INTO EZEN.P_BOARD (POST_NUM, ID, BOARD_NUM, POST_CATE, POST_TITLE, POST_CONTENT)
VALUES(seq_BOARD_num.nextval, 'egg', 1, 15, '계란프라이', '맨날 먹는다.');
COMMIT;


DROP TABLE P_MESSAGE CASCADE CONSTRAINTS;
CREATE TABLE P_MESSAGE (
	MSG_NUM			NUMBER PRIMARY KEY
	, DATE_SENT		DATE DEFAULT SYSDATE NOT NULL	
	, SENDER 		VARCHAR2(20) NOT NULL
	, RECIEVER		VARCHAR2(20) NOT NULL
	, MSG_CONTENT	VARCHAR2(600) NOT NULL
	, MSG_READ		VARCHAR2(20) DEFAULT '읽지않음' NOT NULL
	, FOREIGN KEY(SENDER) REFERENCES P_MEMBER(ID)
	, FOREIGN KEY(RECIEVER) REFERENCES P_MEMBER(ID)
);

INSERT INTO EZEN.P_MESSAGE (MSG_NUM, SENDER, RECIEVER, MSG_CONTENT)
VALUES(seq_MESSAGE_num.nextval, 'apple', 'banana', '바나나 잘 사니');
INSERT INTO EZEN.P_MESSAGE (MSG_NUM, SENDER, RECIEVER, MSG_CONTENT)
VALUES(seq_MESSAGE_num.nextval, 'banana', 'chocolate', '초코렛 까맣다');
INSERT INTO EZEN.P_MESSAGE (MSG_NUM, SENDER, RECIEVER, MSG_CONTENT)
VALUES(seq_MESSAGE_num.nextval, 'chocolate', 'dorazi', '도라지 쓰다');
INSERT INTO EZEN.P_MESSAGE (MSG_NUM, SENDER, RECIEVER, MSG_CONTENT)
VALUES(seq_MESSAGE_num.nextval, 'dorazi', 'egg', '김계란');
INSERT INTO EZEN.P_MESSAGE (MSG_NUM, SENDER, RECIEVER, MSG_CONTENT)
VALUES(seq_MESSAGE_num.nextval, 'egg', 'apple', '애플 떡상');
COMMIT;


DROP TABLE P_COMMENT CASCADE CONSTRAINTS;
CREATE TABLE P_COMMENT (
	COM_NUM				NUMBER PRIMARY KEY
	, ID  				VARCHAR2(20) NOT NULL
	, POST_NUM 			NUMBER NOT NULL
	, COM_CONTENT 		VARCHAR2(300) NOT NULL
	, COM_DATE			DATE DEFAULT SYSDATE NOT NULL
	, PARENT_COM_NUM	NUMBER
	, FOREIGN KEY(ID) REFERENCES P_MEMBER (ID)
	, FOREIGN KEY(POST_NUM) REFERENCES P_BOARD (POST_NUM)
	, FOREIGN KEY(PARENT_COM_NUM) REFERENCES P_COMMENT (COM_NUM)
);

INSERT INTO EZEN.P_COMMENT (COM_NUM, ID, POST_NUM, COM_CONTENT)
VALUES(seq_COMMENT_num.nextval, 'apple', 100005, '나는 사과');
INSERT INTO EZEN.P_COMMENT (COM_NUM, ID, POST_NUM, COM_CONTENT)
VALUES(seq_COMMENT_num.nextval, 'banana', 100004, '나는 바나나');
INSERT INTO EZEN.P_COMMENT (COM_NUM, ID, POST_NUM, COM_CONTENT)
VALUES(seq_COMMENT_num.nextval, 'chocolate', 100003, '나는 초코렛');
INSERT INTO EZEN.P_COMMENT (COM_NUM, ID, POST_NUM, COM_CONTENT)
VALUES(seq_COMMENT_num.nextval, 'dorazi', 100002, '나는 도라지');
INSERT INTO EZEN.P_COMMENT (COM_NUM, ID, POST_NUM, COM_CONTENT)
VALUES(seq_COMMENT_num.nextval, 'egg', 100001, '나는 계란');
COMMIT;

DROP TABLE P_RECOMMEND CASCADE CONSTRAINTS;
CREATE TABLE P_RECOMMEND (
	REC_NUM 		NUMBER PRIMARY KEY
	, ID  			VARCHAR2(20) NOT NULL
	, POST_NUM		NUMBER NOT NULL
	, FOREIGN KEY(ID) REFERENCES P_MEMBER (ID)
	, FOREIGN KEY(POST_NUM) REFERENCES P_BOARD (POST_NUM)
);

INSERT INTO EZEN.P_RECOMMEND (REC_NUM, ID, POST_NUM) VALUES(seq_RECOMMEND_num.nextval, 'apple', 100001);
INSERT INTO EZEN.P_RECOMMEND (REC_NUM, ID, POST_NUM) VALUES(seq_RECOMMEND_num.nextval, 'apple', 100002);
INSERT INTO EZEN.P_RECOMMEND (REC_NUM, ID, POST_NUM) VALUES(seq_RECOMMEND_num.nextval, 'apple', 100003);
INSERT INTO EZEN.P_RECOMMEND (REC_NUM, ID, POST_NUM) VALUES(seq_RECOMMEND_num.nextval, 'banana', 100001);
INSERT INTO EZEN.P_RECOMMEND (REC_NUM, ID, POST_NUM) VALUES(seq_RECOMMEND_num.nextval, 'banana', 100004);
INSERT INTO EZEN.P_RECOMMEND (REC_NUM, ID, POST_NUM) VALUES(seq_RECOMMEND_num.nextval, 'banana', 100005);
INSERT INTO EZEN.P_RECOMMEND (REC_NUM, ID, POST_NUM) VALUES(seq_RECOMMEND_num.nextval, 'chocolate', 100001);
INSERT INTO EZEN.P_RECOMMEND (REC_NUM, ID, POST_NUM) VALUES(seq_RECOMMEND_num.nextval, 'dorazi', 100001);
INSERT INTO EZEN.P_RECOMMEND (REC_NUM, ID, POST_NUM) VALUES(seq_RECOMMEND_num.nextval, 'dorazi', 100002);
INSERT INTO EZEN.P_RECOMMEND (REC_NUM, ID, POST_NUM) VALUES(seq_RECOMMEND_num.nextval, 'egg', 100001);
COMMIT;

DROP TABLE P_REPORT CASCADE CONSTRAINTS;
CREATE TABLE P_REPORT (
	REP_NUM			NUMBER PRIMARY KEY
	, ID  			VARCHAR2(20) NOT NULL
	, POST_NUM		NUMBER 
	, COM_NUM		NUMBER 
	, FOREIGN KEY(ID) REFERENCES P_MEMBER (ID)
	, FOREIGN KEY(POST_NUM) REFERENCES P_BOARD (POST_NUM)
	, FOREIGN KEY(COM_NUM) REFERENCES P_COMMENT (COM_NUM)
);


INSERT INTO EZEN.P_REPORT(REP_NUM, ID, POST_NUM)
VALUES(seq_REPORT_num.nextval, 'apple', 100002);
INSERT INTO EZEN.P_REPORT(REP_NUM, ID, COM_NUM)
VALUES(seq_REPORT_num.nextval, 'banana', 300003);
INSERT INTO EZEN.P_REPORT(REP_NUM, ID, POST_NUM)
VALUES(seq_REPORT_num.nextval, 'chocolate', 100001);
INSERT INTO EZEN.P_REPORT(REP_NUM, ID, COM_NUM)
VALUES(seq_REPORT_num.nextval, 'apple', 300003);
INSERT INTO EZEN.P_REPORT(REP_NUM, ID, POST_NUM)
VALUES(seq_REPORT_num.nextval, 'egg', 100004);
INSERT INTO EZEN.P_REPORT(REP_NUM, ID, COM_NUM)
VALUES(seq_REPORT_num.nextval, 'dorazi', 300005);
INSERT INTO EZEN.P_REPORT(REP_NUM, ID, POST_NUM)
VALUES(seq_REPORT_num.nextval, 'banana', 100003);
COMMIT;


DROP SEQUENCE seq_BOARD_num;
CREATE SEQUENCE seq_BOARD_num
	INCREMENT BY 1					-- 1씩 증가
	START WITH 100001				-- 시작값 10000001
	MINVALUE 100001					-- 최솟값 10000001
	MAXVALUE 200000						-- 최댓값은 무한대
	nocycle							-- 순환하지 않음
	nocache							-- 캐시 안 함 
;

DROP SEQUENCE seq_MESSAGE_num;
CREATE SEQUENCE seq_MESSAGE_num
	INCREMENT BY 1					-- 1씩 증가
	START WITH 200001				-- 시작값 10000001
	MINVALUE 200001					-- 최솟값 10000001
	MAXVALUE 300000							-- 최댓값은 무한대
	nocycle							-- 순환하지 않음
	nocache							-- 캐시 안 함 
;

DROP SEQUENCE seq_COMMENT_num;
CREATE SEQUENCE seq_COMMENT_num
	INCREMENT BY 1					-- 1씩 증가
	START WITH 300001				-- 시작값 10000001
	MINVALUE 300001					-- 최솟값 10000001
	MAXVALUE 400000				-- 최댓값은 무한대
	nocycle							-- 순환하지 않음
	nocache							-- 캐시 안 함 
;

DROP SEQUENCE seq_RECOMMEND_num;
CREATE SEQUENCE seq_RECOMMEND_num
	INCREMENT BY 1					-- 1씩 증가
	START WITH 400001				-- 시작값 10000001
	MINVALUE 400001					-- 최솟값 10000001
	MAXVALUE 500000						-- 최댓값은 무한대
	nocycle							-- 순환하지 않음
	nocache							-- 캐시 안 함 
;
DROP SEQUENCE seq_REPORT_num;
CREATE SEQUENCE seq_REPORT_num
	INCREMENT BY 1					-- 1씩 증가
	START WITH 500001				-- 시작값 10000001
	MINVALUE 500001					-- 최솟값 10000001
	MAXVALUE 600000					-- 최댓값은 무한대
	nocycle							-- 순환하지 않음
	nocache							-- 캐시 안 함 
;

--로그인 
SELECT * FROM P_MEMBER WHERE ID = 'apple';

--아이디 찾기
SELECT * FROM P_MEMBER WHERE EMAIL = 'apple@gmail.com';

--비밀번호 찾기
SELECT * FROM P_MEMBER WHERE ID = 'apple' AND EMAIL = 'apple@gmail.com';
UPDATE P_MEMBER SET PWD = '0824' WHERE ID = 'apple' AND EMAIL = 'apple@gmail.com';
ROLLBACK;

--회원가입
INSERT INTO EZEN.P_MEMBER (ID, PWD, NICK_NM, EMAIL) VALUES('apple', '0001', '사과', 'apple@gmail.com');

--닉네임 수정
UPDATE P_MEMBER SET NICK_NM = 'apple2' WHERE ID = 'apple';
ROLLBACK;

--회원탈퇴 / 회원 제명
DELETE FROM P_REPORT  WHERE ID = 'apple';
DELETE FROM P_RECOMMEND WHERE ID = 'apple';
DELETE FROM P_MESSAGE WHERE SENDER  = 'apple';
DELETE FROM P_MESSAGE WHERE RECIEVER  = 'apple';
DELETE FROM P_COMMENT WHERE ID = 'apple';
DELETE FROM P_BOARD WHERE ID = 'apple';		-- ORA-02292 무결성 제약조건 위배
DELETE FROM P_MEMBER WHERE ID ='apple';		-- ORA-02292 무결성 제약조건 위배
ROLLBACK;
COMMIT;

--	회원 목록보기(관리자)
SELECT * FROM P_MEMBER;

-- 회원 검색(관리자)
SELECT * FROM P_MEMBER WHERE ID = 'apple';
SELECT * FROM P_MEMBER WHERE NICK_NM  = '사과';

-- 목록 정렬(관리자)
SELECT * FROM P_MEMBER ORDER BY JOIN_DATE; 

--게시판 목록 조회(BOARD_NUM: 1 = 정보게시판, 2 = 동행게시판)
SELECT * FROM P_BOARD WHERE BOARD_NUM = 1;

--게시판 카테고리별 조회(POST_CATE: 말머리)
SELECT * FROM P_BOARD WHERE POST_CATE  = 11;

--게시글 검색(제목, 내용, 제목+내용, 작성자)
SELECT * FROM P_BOARD WHERE POST_TITLE LIKE '%사과%';
SELECT * FROM P_BOARD WHERE POST_CONTENT  LIKE '%사과%';
SELECT * FROM P_BOARD WHERE POST_TITLE LIKE '%사과%' OR POST_CONTENT  LIKE '%사과%';
SELECT * FROM P_BOARD WHERE ID LIKE '%apple%';

-- 게시글 쓰기
INSERT INTO EZEN.P_COMMENT (COM_NUM, ID, POST_NUM, COM_CONTENT)
VALUES(seq_COMMENT_num.nextval, 'apple', 100005, '나는 사과');
ROLLBACK;

-- 게시글 수정
UPDATE P_BOARD SET POST_TITLE = '사과 아니다', POST_CONTENT = '진짜 아니다.', POST_CATE = '12', OFILE = 'test.txt'
WHERE POST_NUM = 100001;
ROLLBACK;

-- 조회수 증가
UPDATE P_BOARD SET VISITCOUNT = VISITCOUNT + 1 WHERE POST_NUM = 100001;
ROLLBACK;

-- 게시글 추천
INSERT INTO EZEN.P_RECOMMEND (REC_NUM, ID, POST_NUM) VALUES(seq_RECOMMEND_num.nextval, 'apple', 100001);
ROLLBACK;

-- 게시글 비추천(추천 2번 누를 시)
DELETE FROM P_RECOMMEND WHERE ID = 'apple' AND POST_NUM =100001;
ROLLBACK;

-- 게시글 정렬(추천수순, 조회수순)
SELECT * FROM P_BOARD WHERE BOARD_NUM = 1 ORDER BY VISITCOUNT;

SELECT A.*
	, B.RECOMMEND
FROM P_BOARD A, (
	SELECT COUNT(*) AS RECOMMEND
		, POST_NUM 
	FROM P_RECOMMEND 
	GROUP BY POST_NUM 
	ORDER BY COUNT(*) DESC) B
WHERE A.POST_NUM = B.POST_NUM;
	
-- 게시글 신고 
INSERT INTO EZEN.P_REPORT(REP_NUM, ID, POST_NUM)
VALUES(seq_REPORT_num.nextval, 'apple', 100002);
ROLLBACK;

-- 게시글 신고 취하
DELETE FROM P_REPORT WHERE ID = 'apple' AND POST_NUM =100002;
ROLLBACK;

-- 신고된 게시글 및 댓글 보기(관리자)
SELECT A.*
	, B.REPORT
FROM P_BOARD A, (
	SELECT COUNT(*) AS REPORT
		, POST_NUM
	FROM P_REPORT
	WHERE POST_NUM  IS NOT NULL
	GROUP BY POST_NUM
	) B
WHERE A.POST_NUM = B.POST_NUM
;

-- 쪽지보내기(쪽지쓰기)
INSERT INTO EZEN.P_MESSAGE (MSG_NUM, SENDER, RECIEVER, MSG_CONTENT)
VALUES(seq_MESSAGE_num.nextval, 'apple', 'banana', '바나나 잘 사니');
ROLLBACK;

-- 받은 쪽지함
SELECT * FROM P_MESSAGE WHERE RECIEVER = 'apple';

-- 보낸 쪽지함
SELECT * FROM P_MESSAGE WHERE SENDER = 'apple';

-- 쪽지 보기(읽음상태 변경)
UPDATE P_MESSAGE SET MSG_READ = '읽음' WHERE MSG_NUM = 200001;
ROLLBACK;